print("Program starting.")
Brand = input("Insert car brand: ")
Model = input("Insert car model: ")
print("Car brand is ", Brand, sep='"', end='" ') 
print("and the model is ", Model, sep="'", end="'.\n")
print("Program ending.")